# Generated by Django 5.2.7 on 2025-11-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobil', '0001_initial'),
        ('pelanggan', '0001_initial'),
        ('promo', '0001_initial'),
        ('supir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_booking', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_hari', models.IntegerField(default=1, editable=False)),
                ('harga_total', models.DecimalField(decimal_places=2, help_text='Total setelah diskon + supir', max_digits=12)),
                ('denda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('konfirmasi', 'Dikonfirmasi / Siap Ambil'), ('selesai', 'Selesai / Dikembalikan'), ('batal', 'Dibatalkan')], default='pending', max_length=20)),
                ('type_pesanan', models.CharField(choices=[('online', 'Online (Web)'), ('offline', 'Offline (Walk-in)')], default='online', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('wa_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pesanan', to='mobil.mobil')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pesanan', to='pelanggan.pelanggan')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan', to='promo.promo')),
                ('supir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan', to='supir.supir')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Data Pesanan',
                'db_table': 'pesanan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tanggal_mulai', 'tanggal_selesai'], name='pesanan_tanggal_bdd1c2_idx'), models.Index(fields=['status'], name='pesanan_status_c7ea8f_idx')],
            },
        ),
    ]
