# Generated by Django 5.2.7 on 2025-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0005_mobil_dengan_supir'),
        ('pelanggan', '0003_alter_pelanggan_ktp'),
        ('pesanan', '0001_initial'),
        ('promo', '0001_initial'),
        ('supir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='Centang jika penyewa adalah perusahaan'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='perusahaan_alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='perusahaan_nama',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='perusahaan_npwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='perusahaan_pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama PIC'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='perusahaan_pic_kontak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontak PIC'),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='harga_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total biaya sewa', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('konfirmasi', 'Dikonfirmasi / Siap Ambil'), ('aktif', 'Sedang Disewa'), ('selesai', 'Selesai / Dikembalikan'), ('batal', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='type_pesanan',
            field=models.CharField(choices=[('online', 'Online (Web)'), ('offline', 'Offline (Walk-in/WA)')], default='online', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pesanan',
            index=models.Index(fields=['kode_booking'], name='pesanan_kode_bo_dff941_idx'),
        ),
    ]
