# Generated by Django 5.2.7 on 2025-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0002_pesanan_is_corporate_pesanan_perusahaan_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='bukti_ktp',
            field=models.ImageField(blank=True, help_text='Foto KTP penyewa', null=True, upload_to='ktp_uploads/%Y/%m/'),
        ),
    ]
