# Generated by Django 5.2.7 on 2025-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul kegiatan/foto', max_length=200)),
                ('deskripsi', models.TextField(blank=True, help_text='Cerita singkat dibalik foto/video ini', null=True)),
                ('file_media', models.FileField(help_text='Upload Foto (.jpg/.png) atau Video (.mp4)', upload_to='website/dokumentasi/')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampilan (0 paling awal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galeri Dokumentasi',
                'verbose_name_plural': 'Galeri Dokumentasi',
                'ordering': ['urutan', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul besar di tengah layar', max_length=200)),
                ('sub_judul', models.TextField(blank=True, help_text='Deskripsi singkat di bawah judul', null=True)),
                ('background_media', models.FileField(help_text='Upload Video (mp4/webm) atau Gambar (jpg/png)', upload_to='website/hero/')),
                ('is_active', models.BooleanField(default=True, help_text='Jika dicentang, slide ini akan tampil')),
                ('urutan', models.IntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Hero',
                'verbose_name_plural': 'Konfigurasi Hero',
                'ordering': ['urutan', '-created_at'],
            },
        ),
    ]
