# Generated by Django 5.2.7 on 2026-01-03 06:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasi',
            name='file_media',
            field=cloudinary.models.CloudinaryField(help_text='Upload Foto (.jpg/.png) atau Video (.mp4)', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_media',
            field=cloudinary.models.CloudinaryField(help_text='Upload Video (mp4/webm) atau Gambar (jpg/png)', max_length=255, verbose_name='image'),
        ),
    ]
