# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('ktp', models.CharField(help_text='Nomor Induk Kependudukan (NIK)', max_length=50, unique=True)),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='pelanggan/ktp/')),
                ('foto_sim', models.ImageField(blank=True, null=True, upload_to='pelanggan/sim/')),
                ('catatan', models.TextField(blank=True, help_text='Catatan khusus admin (misal: blacklist)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Data Pelanggan',
                'db_table': 'pelanggan',
                'ordering': ['-created_at'],
            },
        ),
    ]
