# Generated by Django 5.2.7 on 2025-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='ktp',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan (NIK)', max_length=50, null=True, unique=True),
        ),
    ]
