# Generated by Django 5.2.7 on 2025-12-09 20:30

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0004_alter_pelanggan_ktp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='ktp',
            field=models.CharField(blank=True, help_text='Harus 16 digit sesuai KTP', max_length=50, null=True, unique=True, validators=[users.validators.validate_indonesian_nik]),
        ),
    ]
