# Generated by Django 5.2.7 on 2025-12-11 10:18

import pelanggan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0005_alter_pelanggan_ktp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='foto_ktp',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='bukti_ktp',
            field=models.ImageField(blank=True, help_text='Foto KTP Asli', null=True, upload_to=pelanggan.models.upload_location),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
