# Generated by Django 5.2.7 on 2025-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0006_remove_pelanggan_foto_ktp_pelanggan_bukti_ktp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='bukti_ktp',
            field=models.ImageField(blank=True, help_text='Foto KTP Asli', null=True, upload_to=''),
        ),
    ]
