# Generated by Django 5.2.7 on 2025-12-11 10:50

import pelanggan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0007_alter_pelanggan_bukti_ktp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='bukti_ktp',
            field=models.ImageField(blank=True, help_text='Foto KTP Asli', null=True, upload_to=pelanggan.models.upload_location),
        ),
    ]
