# Generated by Django 5.2.7 on 2025-12-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0008_alter_pelanggan_bukti_ktp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelanggan',
            old_name='bukti_ktp',
            new_name='foto_ktp',
        ),
    ]
