# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, default=150000, max_digits=12)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia / Standby'), ('bertugas', 'Sedang Bertugas'), ('off', 'Libur / Off')], default='tersedia', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='supir/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supir',
                'verbose_name_plural': 'Data Supir',
                'db_table': 'supir',
                'ordering': ['nama'],
            },
        ),
    ]
