# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode unik, misal: LEBARAN2025', max_length=20, unique=True)),
                ('nama_promo', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('nominal_potongan', models.DecimalField(decimal_places=2, help_text='Besar potongan dalam Rupiah', max_digits=12)),
                ('min_transaksi', models.DecimalField(decimal_places=2, default=0, help_text='Minimal total belanja agar promo bisa dipakai', max_digits=12)),
                ('berlaku_mulai', models.DateField()),
                ('berlaku_sampai', models.DateField()),
                ('aktif', models.BooleanField(default=True, help_text='Matikan jika ingin menonaktifkan promo secara manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Data Promo',
                'db_table': 'promo',
                'ordering': ['-berlaku_sampai'],
            },
        ),
    ]
