# Generated by Django 5.2.7 on 2025-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='nominal_potongan',
        ),
        migrations.AddField(
            model_name='promo',
            name='kuota',
            field=models.PositiveIntegerField(default=0, help_text='Batas jumlah penggunaan promo. Isi 0 jika unlimited.'),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_potongan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maksimal potongan (khusus tipe persen). Isi 0 jika tidak ada batas.', max_digits=12),
        ),
        migrations.AddField(
            model_name='promo',
            name='nilai_diskon',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Masukkan nominal Rp atau angka Persen', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='sudah_digunakan',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Jumlah kali promo ini sudah dipakai'),
        ),
        migrations.AddField(
            model_name='promo',
            name='tipe_diskon',
            field=models.CharField(choices=[('nominal', 'Nominal (Rp)'), ('persen', 'Persentase (%)')], default='nominal', max_length=10),
        ),
        migrations.AlterField(
            model_name='promo',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='berlaku_mulai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='berlaku_sampai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='kode',
            field=models.CharField(help_text='Kode unik (otomatis uppercase)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='min_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
