# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode', models.CharField(choices=[('transfer', 'Transfer Bank'), ('cash', 'Tunai / Cash')], default='transfer', max_length=20)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('lunas', 'Lunas / Terverifikasi'), ('gagal', 'Gagal / Ditolak')], default='pending', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Data Pembayaran',
                'db_table': 'pembayaran',
            },
        ),
    ]
