# Generated by Django 5.2.7 on 2025-11-21 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pembayaran', '0001_initial'),
        ('pesanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='dicatat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_dicatat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='pesanan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='pesanan.pesanan'),
        ),
    ]
