# Generated by Django 5.2.7 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mobil', models.CharField(max_length=100)),
                ('merk', models.CharField(max_length=100)),
                ('jenis', models.CharField(blank=True, max_length=50, null=True)),
                ('plat_nomor', models.CharField(max_length=20, unique=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('transmisi', models.CharField(choices=[('manual', 'Manual'), ('matic', 'Automatic')], default='manual', max_length=10)),
                ('kapasitas_kursi', models.IntegerField(default=4, help_text='Jumlah maksimal penumpang')),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=12)),
                ('denda_per_jam', models.DecimalField(decimal_places=2, default=50000, help_text='Denda jika telat kembalikan', max_digits=12)),
                ('status', models.CharField(choices=[('aktif', 'Aktif / Siap Sewa'), ('servis', 'Sedang Servis / Bengkel'), ('nonaktif', 'Non-Aktif / Arsip')], default='aktif', max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='mobil/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobil',
                'verbose_name_plural': 'Data Mobil',
                'db_table': 'mobil',
                'ordering': ['-created_at'],
            },
        ),
    ]
