# Generated by Django 5.2.7 on 2025-12-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobil',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mobil',
            name='popularity',
            field=models.CharField(choices=[('standard', 'Standard'), ('bestseller', 'Best Seller'), ('hotdeal', 'Hot Deal'), ('new', 'New Arrival'), ('recommended', 'Rekomendasi')], default='standard', help_text='Label marketing untuk mobil ini', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='denda_per_jam',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='kapasitas_kursi',
            field=models.IntegerField(default=4),
        ),
    ]
