# Generated by Django 5.2.7 on 2025-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0002_alter_mobil_options_mobil_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='plat_nomor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
