# Generated by Django 5.2.7 on 2025-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0003_alter_mobil_plat_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='merk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
