# Generated by Django 5.2.7 on 2025-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0004_alter_mobil_merk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='dengan_supir',
            field=models.BooleanField(default=False, help_text='Ceklis jika harga sudah termasuk supir (All In)'),
        ),
    ]
