# Generated by Django 5.2.7 on 2025-12-30 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0005_mobil_dengan_supir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='gambar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
